/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "kademlia.pb-c.h"
void   node_info__init
                     (NodeInfo         *message)
{
  static NodeInfo init_value = NODE_INFO__INIT;
  *message = init_value;
}
size_t node_info__get_packed_size
                     (const NodeInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_info__pack
                     (const NodeInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_info__pack_to_buffer
                     (const NodeInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeInfo *
       node_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeInfo *)
     protobuf_c_message_unpack (&node_info__descriptor,
                                allocator, len, data);
}
void   node_info__free_unpacked
                     (NodeInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &node_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   store__init
                     (Store         *message)
{
  static Store init_value = STORE__INIT;
  *message = init_value;
}
size_t store__get_packed_size
                     (const Store *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t store__pack
                     (const Store *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t store__pack_to_buffer
                     (const Store *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Store *
       store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Store *)
     protobuf_c_message_unpack (&store__descriptor,
                                allocator, len, data);
}
void   store__free_unpacked
                     (Store *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   store_reply__init
                     (StoreReply         *message)
{
  static StoreReply init_value = STORE_REPLY__INIT;
  *message = init_value;
}
size_t store_reply__get_packed_size
                     (const StoreReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t store_reply__pack
                     (const StoreReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t store_reply__pack_to_buffer
                     (const StoreReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StoreReply *
       store_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StoreReply *)
     protobuf_c_message_unpack (&store_reply__descriptor,
                                allocator, len, data);
}
void   store_reply__free_unpacked
                     (StoreReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &store_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_close_nodes__init
                     (FindCloseNodes         *message)
{
  static FindCloseNodes init_value = FIND_CLOSE_NODES__INIT;
  *message = init_value;
}
size_t find_close_nodes__get_packed_size
                     (const FindCloseNodes *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_close_nodes__pack
                     (const FindCloseNodes *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_close_nodes__pack_to_buffer
                     (const FindCloseNodes *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindCloseNodes *
       find_close_nodes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindCloseNodes *)
     protobuf_c_message_unpack (&find_close_nodes__descriptor,
                                allocator, len, data);
}
void   find_close_nodes__free_unpacked
                     (FindCloseNodes *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_close_nodes_reply__init
                     (FindCloseNodesReply         *message)
{
  static FindCloseNodesReply init_value = FIND_CLOSE_NODES_REPLY__INIT;
  *message = init_value;
}
size_t find_close_nodes_reply__get_packed_size
                     (const FindCloseNodesReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_close_nodes_reply__pack
                     (const FindCloseNodesReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_close_nodes_reply__pack_to_buffer
                     (const FindCloseNodesReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindCloseNodesReply *
       find_close_nodes_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindCloseNodesReply *)
     protobuf_c_message_unpack (&find_close_nodes_reply__descriptor,
                                allocator, len, data);
}
void   find_close_nodes_reply__free_unpacked
                     (FindCloseNodesReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_close_nodes_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_value__init
                     (FindValue         *message)
{
  static FindValue init_value = FIND_VALUE__INIT;
  *message = init_value;
}
size_t find_value__get_packed_size
                     (const FindValue *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_value__pack
                     (const FindValue *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_value__pack_to_buffer
                     (const FindValue *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindValue *
       find_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindValue *)
     protobuf_c_message_unpack (&find_value__descriptor,
                                allocator, len, data);
}
void   find_value__free_unpacked
                     (FindValue *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_value_reply__init
                     (FindValueReply         *message)
{
  static FindValueReply init_value = FIND_VALUE_REPLY__INIT;
  *message = init_value;
}
size_t find_value_reply__get_packed_size
                     (const FindValueReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_value_reply__pack
                     (const FindValueReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_value_reply__pack_to_buffer
                     (const FindValueReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindValueReply *
       find_value_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindValueReply *)
     protobuf_c_message_unpack (&find_value_reply__descriptor,
                                allocator, len, data);
}
void   find_value_reply__free_unpacked
                     (FindValueReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &find_value_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node_info__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeInfo, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeInfo, port),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "cert",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeInfo, cert),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "pbc",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeInfo, pbc),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "ip",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NodeInfo, ip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned node_info__field_indices_by_name[] = {
  2,   /* field[2] = cert */
  0,   /* field[0] = id */
  4,   /* field[4] = ip */
  3,   /* field[3] = pbc */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange node_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor node_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "node_info",
  "NodeInfo",
  "NodeInfo",
  "",
  sizeof(NodeInfo),
  5,
  node_info__field_descriptors,
  node_info__field_indices_by_name,
  1,  node_info__number_ranges,
  (ProtobufCMessageInit) node_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor store__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Store, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Store, data),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "self",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Store, self),
    &node_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned store__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = key */
  2,   /* field[2] = self */
};
static const ProtobufCIntRange store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor store__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "store",
  "Store",
  "Store",
  "",
  sizeof(Store),
  3,
  store__field_descriptors,
  store__field_indices_by_name,
  1,  store__number_ranges,
  (ProtobufCMessageInit) store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor store_reply__field_descriptors[1] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StoreReply, success),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned store_reply__field_indices_by_name[] = {
  0,   /* field[0] = success */
};
static const ProtobufCIntRange store_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor store_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "store_reply",
  "StoreReply",
  "StoreReply",
  "",
  sizeof(StoreReply),
  1,
  store_reply__field_descriptors,
  store_reply__field_indices_by_name,
  1,  store_reply__number_ranges,
  (ProtobufCMessageInit) store_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_close_nodes__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FindCloseNodes, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "self",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FindCloseNodes, self),
    &node_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned find_close_nodes__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = self */
};
static const ProtobufCIntRange find_close_nodes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor find_close_nodes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "find_close_nodes",
  "FindCloseNodes",
  "FindCloseNodes",
  "",
  sizeof(FindCloseNodes),
  2,
  find_close_nodes__field_descriptors,
  find_close_nodes__field_indices_by_name,
  1,  find_close_nodes__number_ranges,
  (ProtobufCMessageInit) find_close_nodes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_close_nodes_reply__field_descriptors[1] =
{
  {
    "nodes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(FindCloseNodesReply, n_nodes),
    PROTOBUF_C_OFFSETOF(FindCloseNodesReply, nodes),
    &node_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned find_close_nodes_reply__field_indices_by_name[] = {
  0,   /* field[0] = nodes */
};
static const ProtobufCIntRange find_close_nodes_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor find_close_nodes_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "find_close_nodes_reply",
  "FindCloseNodesReply",
  "FindCloseNodesReply",
  "",
  sizeof(FindCloseNodesReply),
  1,
  find_close_nodes_reply__field_descriptors,
  find_close_nodes_reply__field_indices_by_name,
  1,  find_close_nodes_reply__number_ranges,
  (ProtobufCMessageInit) find_close_nodes_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_value__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FindValue, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "self",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FindValue, self),
    &node_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned find_value__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = self */
};
static const ProtobufCIntRange find_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor find_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "find_value",
  "FindValue",
  "FindValue",
  "",
  sizeof(FindValue),
  2,
  find_value__field_descriptors,
  find_value__field_indices_by_name,
  1,  find_value__number_ranges,
  (ProtobufCMessageInit) find_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_value_reply__field_descriptors[3] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FindValueReply, success),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(FindValueReply, n_nodes),
    PROTOBUF_C_OFFSETOF(FindValueReply, nodes),
    &node_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(FindValueReply, has_data),
    PROTOBUF_C_OFFSETOF(FindValueReply, data),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned find_value_reply__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = nodes */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange find_value_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor find_value_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "find_value_reply",
  "FindValueReply",
  "FindValueReply",
  "",
  sizeof(FindValueReply),
  3,
  find_value_reply__field_descriptors,
  find_value_reply__field_indices_by_name,
  1,  find_value_reply__number_ranges,
  (ProtobufCMessageInit) find_value_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
