/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_setuppackage_2eproto__INCLUDED
#define PROTOBUF_C_setuppackage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _DummySetupPackage DummySetupPackage;
typedef struct _RoutingTableEntry RoutingTableEntry;
typedef struct _SetupPackage SetupPackage;
typedef struct _SetupArray SetupArray;


/* --- enums --- */


/* --- messages --- */

struct  _DummySetupPackage
{
  ProtobufCMessage base;
  ProtobufCBinaryData seed;
  uint32_t size;
  uint32_t flags;
};
#define DUMMY_SETUP_PACKAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dummy_setup_package__descriptor) \
    , {0,NULL}, 0, 0 }


struct  _RoutingTableEntry
{
  ProtobufCMessage base;
  ProtobufCBinaryData ap_adress;
  size_t n_ip_adresses;
  char **ip_adresses;
  size_t n_ports;
  uint32_t *ports;
};
#define ROUTING_TABLE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&routing_table_entry__descriptor) \
    , {0,NULL}, 0,NULL, 0,NULL }


struct  _SetupPackage
{
  ProtobufCMessage base;
  char *prev_ip;
  char *next_ip;
  uint32_t prev_port;
  uint32_t next_port;
  ProtobufCBinaryData prev_id;
  ProtobufCBinaryData next_id;
  ProtobufCBinaryData prev_communication_certificate_flat;
  ProtobufCBinaryData next_communication_certificate_flat;
  ProtobufCBinaryData construction_certificate_flat;
  size_t n_dummies;
  DummySetupPackage **dummies;
  uint32_t nkeys;
  ProtobufCBinaryData key_seed;
  ProtobufCBinaryData replacement_seed;
  ProtobufCBinaryData key_salt;
  uint32_t flags;
  ProtobufCBinaryData hash;
  ProtobufCBinaryData external_hash;
  protobuf_c_boolean has_ap_adress;
  ProtobufCBinaryData ap_adress;
  RoutingTableEntry *rte;
};
#define SETUP_PACKAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setup_package__descriptor) \
    , NULL, NULL, 0, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0,NULL, 0, {0,NULL}, {0,NULL}, {0,NULL}, 0, {0,NULL}, {0,NULL}, 0,{0,NULL}, NULL }


struct  _SetupArray
{
  ProtobufCMessage base;
  size_t n_slots;
  ProtobufCBinaryData *slots;
};
#define SETUP_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setup_array__descriptor) \
    , 0,NULL }


/* DummySetupPackage methods */
void   dummy_setup_package__init
                     (DummySetupPackage         *message);
size_t dummy_setup_package__get_packed_size
                     (const DummySetupPackage   *message);
size_t dummy_setup_package__pack
                     (const DummySetupPackage   *message,
                      uint8_t             *out);
size_t dummy_setup_package__pack_to_buffer
                     (const DummySetupPackage   *message,
                      ProtobufCBuffer     *buffer);
DummySetupPackage *
       dummy_setup_package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dummy_setup_package__free_unpacked
                     (DummySetupPackage *message,
                      ProtobufCAllocator *allocator);
/* RoutingTableEntry methods */
void   routing_table_entry__init
                     (RoutingTableEntry         *message);
size_t routing_table_entry__get_packed_size
                     (const RoutingTableEntry   *message);
size_t routing_table_entry__pack
                     (const RoutingTableEntry   *message,
                      uint8_t             *out);
size_t routing_table_entry__pack_to_buffer
                     (const RoutingTableEntry   *message,
                      ProtobufCBuffer     *buffer);
RoutingTableEntry *
       routing_table_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   routing_table_entry__free_unpacked
                     (RoutingTableEntry *message,
                      ProtobufCAllocator *allocator);
/* SetupPackage methods */
void   setup_package__init
                     (SetupPackage         *message);
size_t setup_package__get_packed_size
                     (const SetupPackage   *message);
size_t setup_package__pack
                     (const SetupPackage   *message,
                      uint8_t             *out);
size_t setup_package__pack_to_buffer
                     (const SetupPackage   *message,
                      ProtobufCBuffer     *buffer);
SetupPackage *
       setup_package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setup_package__free_unpacked
                     (SetupPackage *message,
                      ProtobufCAllocator *allocator);
/* SetupArray methods */
void   setup_array__init
                     (SetupArray         *message);
size_t setup_array__get_packed_size
                     (const SetupArray   *message);
size_t setup_array__pack
                     (const SetupArray   *message,
                      uint8_t             *out);
size_t setup_array__pack_to_buffer
                     (const SetupArray   *message,
                      ProtobufCBuffer     *buffer);
SetupArray *
       setup_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setup_array__free_unpacked
                     (SetupArray *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DummySetupPackage_Closure)
                 (const DummySetupPackage *message,
                  void *closure_data);
typedef void (*RoutingTableEntry_Closure)
                 (const RoutingTableEntry *message,
                  void *closure_data);
typedef void (*SetupPackage_Closure)
                 (const SetupPackage *message,
                  void *closure_data);
typedef void (*SetupArray_Closure)
                 (const SetupArray *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dummy_setup_package__descriptor;
extern const ProtobufCMessageDescriptor routing_table_entry__descriptor;
extern const ProtobufCMessageDescriptor setup_package__descriptor;
extern const ProtobufCMessageDescriptor setup_array__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_setuppackage_2eproto__INCLUDED */
